# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e45f8e790cd417c220ce3732ee689d1d9dcd221898f3ca583e1a014e05cf47ad81258f9f04b84041efb280c2ee4a5da15072ffff19413357c4227c49afe9d1d0

test:
  secret_key_base: 607a4f73bcea78e6abb2565e174a6bc8ab467f9f71fd68cbcd4f56c9d9c5b6b6790a920f8a855f7860f7a0baa41e7c868abf5c298607cac551bce9c9f163d2e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
